### ISSUE TITLE
Add LLM Analysis

### ISSUE THREAD

**Issue by Lucs1590** [Lucs1590/strava-to-trainingpeaks#4]
## Description
The idea is that after converting the file to be exported to training peaks, ask the athlete if he wants to have feedback from an LLM (GPT4 or SportBERT) regarding the training performed.
At first I would send the entire tcx file, but the number of tokens would be very high and the service would be very expensive. Therefore, the idea is to summarize by points (as in the medium article) and send this in the prompt for LLM to analyze.
If the user chooses that he wants to have the LLM analysis, add the question "was there anything planned for this training?" so that this will also enrich the prompt.

## TO-DO
- [x] Parse the tcx or gpx file;
- [x] Test both LLMs;
- [ ] Write LinkedIn and Medium post.

## Prompt
Based on the following data that is related to a {sport} training session, carry out an analysis highlighting positive points, where the athlete did well and where he did poorly and what he can do to improve in the next {sport}.

<data>
Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.
</data>

## Resources
- https://towardsdatascience.com/parsing-fitness-tracker-data-with-python-a59e7dc17418
- https://huggingface.co/microsoft/SportsBERT
- https://pypi.org/project/tcx2gpx/

**Comment by Lucs1590** [comment]
- https://stackoverflow.com/questions/13703720/converting-between-datetime-timestamp-and-datetime64
- https://stackoverflow.com/questions/56838488/find-similar-rows-based-on-mixed-datatypes-in-pandas-dataframe
